### ISSUE TITLE
ipsw macho patch can only handle 1 build tool for LC_BUILD_VERSION

### ISSUE THREAD

**Issue by saagarjha** [blacktop/ipsw#403] opened 2024-02-11 09:31 UTC
### What happened?

A Mach-O file can have between 0 and ~unlimited build tools. However `ipsw macho patch` requires exactly one: https://github.com/blacktop/ipsw/blob/1e8a8bc1a86366ee247dec921515a7bfb53f7f44/cmd/ipsw/cmd/macho/macho_patch.go#L152

### How can we reproduce this?

```console
$ ipsw macho patch mod MACHO LC_BUILD_VERSION iOS 16.3 16.3
? You are about to overwrite MACHO. Continue? Yes
   • Modifying load command LC_BUILD_VERSION in MACHO
   ⨯ failed to patch MachO file: not enough arguments for adding LC_BUILD_VERSION; must supply PLATFORM, MINOS, SDK strings and TOOL, TOOL_VERSION strings
```

### ipsw version

```bash
Version: , BuildTime: 20240208
```

### Search

- [X] I did search for other open and closed issues before opening this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by blacktop** [comment] 2024-02-11 18:38
I believe I have fixed the `ipsw` code now, however, I believe there still exists a 🐛 in go-macho's export.go functionality that needs a closer look when adding/manipulating LCs etc.  

The reason I hid the `ipsw dsc extract` cmd was reports of it creating dylibs w/ sections that IDA Pro didn't like.

I don't use the functionality that much myself, but it's something I need to fix (as it also affects the `ipsw macho patch` cmd.

If you have any interest/time I'd ❤️ some help w/ it.  Otherwise I'll keep this issue open until I can confirm it's good.

Thanks again for reporting this issue.

**Comment by blacktop** [comment] 2024-03-29 18:25
Started looking at `go-macho`'s Export and remembered that the `ipsw macho patch` cmd uses the Save func not the Export so this should be fine (unless you added so many NEW LCs that it had to resize the segment so closing.

**Closed by blacktop** 2024-03-29 18:25 UTC
Labels: bug
